version: '3'
services:
  strongbox-web-integration-tests-gradle:
    image: strongboxci/alpine:jdk8-mvn3.6-gradle6.6
    volumes:
      - $HOME/.m2/repository:/home/jenkins/.m2/repository
      - ../:/workspace
    working_dir: /workspace/gradle
    command: mvn clean install -e
